version: '3'

services:
  patientor-api:
    build:
      context: ./server
      dockerfile: ./dev.Dockerfile
    image: patientor-api:alpine-dev
    ports:
      - 3001
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    container_name: patientor-api
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  redis:
    image: redis
    volumes:
      - redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    container_name: patientor-db
  patientor:
    build: ./client
    image: patientor
    ports:
      - 3000
    container_name: patientor
    command: sleep infinity

volumes:
  redis:
