version: '3'

services:
  patientor-backend:
    build: ./server
    image: patientor-backend
    ports:
      - 3001
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    container_name: patientor-server
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
  redis:
    image: redis
    volumes:
      - redis:/data
    command: ["redis-server", "--appendonly", "yes"]
    container_name: patientor-db
  patientor-frontend:
    build: ./client
    image: patientor-frontend
    ports:
      - 3000
    container_name: patientor-client
    command: sleep infinity

volumes:
  redis:
