version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2020.01
    steps:
      - checkout
      # must setup remote docker to use docker-cli in a circleci docker executor
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            cd server
            docker build -t registry.heroku.com/patientor-api/web -f prod.Dockerfile .
      - run:
          name: Push Docker image to Heroku
          # must escape here doc symbols for 2.1+ config
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh
            cat >~/.netrc \<< EOF
            machine api.heroku.com
              login $HEROKU_EMAIL
              password $HEROKU_TOKEN
            EOF
            heroku container:login
            heroku config:set --app=patientor-api \
              REDIS_HOST=$REDIS_HOST \
              REDIS_PORT=$REDIS_PORT \
              REDIS_PASSWORD=$REDIS_PASSWORD
            docker push registry.heroku.com/patientor-api/web
            heroku container:release web



